# Generated by Django 3.2.23 on 2024-01-12 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240111_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='datastructures',
            field=models.ManyToManyField(to='core.Datastructure'),
        ),
    ]
