# Generated by Django 3.2.23 on 2024-01-13 17:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240112_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.pattern_image_file_path),
        ),
    ]
